### ISSUE TITLE
1 catastrophic error detected in the compilation of "kernel.cu.cu". Compilation terminated.

### ISSUE THREAD

**Issue by jasonwu-1** [FindDefinition/cumm#19]
While running test_nvrtc2() in cutest_nvrtc.py ,I encountered the error below, and my cuda version is 11.3. I've tested on cuda11.6 and cuda 11.7, the same error occured. Is anything missing from my environment causing this error? I'd really appreciate your reply.

```
1 catastrophic error detected in the compilation of "kernel.cu.cu".
Compilation terminated.

Traceback (most recent call last):
  File "/home/jason/Code/RayModel-main/test/cutest_nvrtc.py", line 262, in <module>
    test_nvrtc2()
  File "/home/jason/Code/RayModel-main/test/cutest_nvrtc.py", line 77, in test_nvrtc2
    inliner.kernel_1d("wtf", keys.dim(0), 0, f"""
  File "/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/cumm/inliner/__init__.py", line 395, in kernel_1d
    return self.inline(name,
  File "/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/pccm/builder/inliner.py", line 777, in inline
    func = self.build(pccm_class, mod_root, name, timeout,
  File "/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/cumm/inliner/__init__.py", line 352, in build
    mod = CummNVRTCModuleBase.from_params(params)
  File "/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/cumm/nvrtc/__init__.py", line 274, in from_params
    return cls(params.code,
  File "/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/cumm/nvrtc/__init__.py", line 208, in __init__
    super().__init__(code,
  File "/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/cumm/tensorview/__init__.py", line 174, in __init__
    self._mod = _NVRTCModule(code, headers, opts, program_name,
RuntimeError: /io/include/tensorview/cuda/nvrtc.h(96)
compileResult == NVRTC_SUCCESS assert faild. nvrtc compile failed.
```

**Comment by jasonwu-1** [comment]
```
/home/jason/anaconda3/envs/cuda113/bin/python /home/jason/Code/RayModel-main/test/cutest_nvrtc.py
/home/jason/anaconda3/envs/cuda113/lib/python3.8/site-packages/cumm/include/tensorview/core/nvrtc/core.h(27): catastrophic error: cannot open source file "cuda/std/cassert"
```

**Comment by FindDefinition** [comment]
you need to install cuda to your system or install libcudacxx (available in github) headers to your system.

**Comment by jasonwu-1** [comment]
Thanks. I only had the cuda came with pytorch-gpu before, installing the nvidia cuda toolkit fixed my problem.
