### ISSUE TITLE
TENSORVIEW_INCLUDE_PATH does not exist

### ISSUE THREAD

**Issue by jonasmeyer1** [FindDefinition/cumm#2]
Hi,

I built a wheel form source  for the usage with spconv 2.x on a Nvidia Jetson TX2 with the following specifications:
Ubuntu 18.04
CUDA 10.2
Python 3.6
Pytorch 1.6.0

I followed the description in the README and did not export ```CUMM_CUDA_VERSION```.  Additionally I specified the CUDA compute capability by ```export CUMM_CUDA_ARCH_LIST="6.2"``` as described in [spconv](https://github.com/traveller59/spconv).

I could build and install the wheel without any problems, but I got the following AssertionError, when importing cumm in python.

```
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cumm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/.local/lib/python3.6/site-packages/cumm/__init__.py", line 20, in <module>
    from .constants import PACKAGE_NAME, CUMM_DISABLE_JIT, CUMM_CPU_ONLY_BUILD
  File "/home/nvidia/.local/lib/python3.6/site-packages/cumm/constants.py", line 33, in <module>
    assert TENSORVIEW_INCLUDE_PATH.exists()
AssertionError

```

**Comment by FindDefinition** [comment]
Could you share your build command? ```python setup.py install``` or ```python setup.py bdist_wheel```

**Comment by jonasmeyer1** [comment]
I ran ```sudo python3 setup.py bdist_wheel```

If I run it without sudo privilegies I get the following error:
```
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    ext_modules=ext_modules,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/extension.py", line 59, in run
    self.build_extension(ext)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/extension.py", line 90, in build_extension
    debug_file_gen=ext.debug_file_gen)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/builder/pybind.py", line 56, in build_pybind
    user_cus = cg.build_graph(cus, namespace_root)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/core/__init__.py", line 1828, in build_graph
    cu_type_to_cu[dep] = dep()
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/core/__init__.py", line 824, in wrapper
    func(self, *args, **kwargs)
  File "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/cumm/cumm/common.py", line 181, in __init__
    gpu_arch_flags = _get_cuda_arch_flags()
  File "/media/7c1b8284-04e8-4feb-9dce-c3ceeda85c2e/MTH_meyj/Software/cumm/cumm/common.py", line 168, in _get_cuda_arch_flags
    f"Unknown CUDA arch ({arch}) or GPU not supported")
ValueError: Unknown CUDA arch (6.2) or GPU not supported
```

**Comment by FindDefinition** [comment]
You can add '6.2' to this [line](https://github.com/FindDefinition/cumm/blob/main/cumm/common.py#L85)
If you built with sudo, the exported env won't be forward to sudo command, so ```CUMM_CUDA_ARCH_LIST``` isn't used, the build process should fail.

**Comment by jonasmeyer1** [comment]
Thanks for the hint. When adding '6.2' the compilation went a step further.

I receive now the following error:

```
/usr/bin/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    ext_modules=ext_modules,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/extension.py", line 59, in run
    self.build_extension(ext)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/extension.py", line 90, in build_extension
    debug_file_gen=ext.debug_file_gen)
  File "/home/nvidia/.local/lib/python3.6/site-packages/pccm/builder/pybind.py", line 141, in build_pybind
    objects_folder=objects_folder)
  File "/home/nvidia/.local/lib/python3.6/site-packages/ccimport/core.py", line 178, in ccimport
    objects_folder=objects_folder)
  File "/home/nvidia/.local/lib/python3.6/site-packages/ccimport/buildtools/writer.py", line 960, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

```
Do you have any idea how to solve it?
Thanks in advance.

**Comment by FindDefinition** [comment]
You need to check cuda path in [this line](https://github.com/FindDefinition/cumm/blob/main/cumm/common.py#L195), modify it if necessary. I don't know where is cuda root in your environment.

**Comment by jonasmeyer1** [comment]
It works. Thank you very much

**Comment by Hetali-Vekariya** [comment]
I am getting this error while I run import spconv

```
(mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch/second/spconv$ python
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/Mon/second.pytorch/second/spconv/spconv/__init__.py", line 17, in <module>
    from .core import ConvAlgo, AlgoHint
  File "/mnt/data/Mon/second.pytorch/second/spconv/spconv/core.py", line 15, in <module>
    from cumm.gemm.main import gen_shuffle_params_v2 as gen_shuffle_params, GemmAlgoParams
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cumm/__init__.py", line 21, in <module>
    from .constants import CUMM_CPU_ONLY_BUILD, CUMM_DISABLE_JIT, PACKAGE_NAME
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cumm/constants.py", line 35, in <module>
    assert TENSORVIEW_INCLUDE_PATH.exists()
AssertionError
>>>
```

Can you please help me here?
