### ISSUE TITLE
AttributeError: 'BuildMeta' object has no attribute 'includes'

### ISSUE THREAD

**Issue by delightsomeness** [FindDefinition/cumm#25]
When I want to run the following command:
 "python setup.py bdist_wheel" 
My terminal returns an error as follows:
(openpcdet) wheeltec@wheeltec:~/Downloads/cumm-0.2.9$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
copying cumm/__version__.py -> build/lib.linux-aarch64-3.6/cumm
running egg_info
writing cumm_cu102.egg-info/PKG-INFO
writing dependency_links to cumm_cu102.egg-info/dependency_links.txt
writing entry points to cumm_cu102.egg-info/entry_points.txt
writing requirements to cumm_cu102.egg-info/requires.txt
writing top-level names to cumm_cu102.egg-info/top_level.txt
reading manifest file 'cumm_cu102.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'cumm_cu102.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    ext_modules=ext_modules,
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/pccm/extension.py", line 59, in run
    self.build_extension(ext)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/pccm/extension.py", line 90, in build_extension
    debug_file_gen=ext.debug_file_gen)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/pccm/builder/pybind.py", line 45, in build_pybind
    user_cus = cg.build_graph(cus, namespace_root)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/pccm/core/__init__.py", line 2128, in build_graph
    cu_type(), buildmeta_inherit=dep_obj.buildmeta_inherit)
  File "/home/wheeltec/miniforge3/envs/openpcdet/lib/python3.6/site-packages/pccm/core/__init__.py", line 966, in wrapper
    func(self, *args, **kwargs)
  File "/home/wheeltec/Downloads/cumm-0.2.9/cumm/common.py", line 232, in __init__
    self.build_meta.includes.append(TENSORVIEW_INCLUDE_PATH)
AttributeError: 'BuildMeta' object has no attribute 'includes'

Is there any way to solve this error?

**Comment by delightsomeness** [comment]
Remove the 'build' folder and then rerun the compilation command to achieve success.

**Comment by YuRui-Learning** [comment]
Hi followed your instructions and I didn't solve the problem, still experiencing this issue

**Comment by crrasjtu** [comment]
> Hi followed your instructions and I didn't solve the problem, still experiencing this issue

I have solved the problem. This is due to the mismatch between the versions of pccm and ccimport and cumm. The overall installation version is pccm==0.3.4, ccimport==0.3.7, cumm==0.2.8, and the wheel library needs to be included
