### ISSUE TITLE
cann't   install    cumm   in  jetson agx xavier  arrch64   

### ISSUE THREAD

**Issue by AI-liu** [FindDefinition/cumm#4]
sudo pip3 install -e .

python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cumm
[1/36] g++ -MMD -MT /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch -MF /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch.d -I "/home/cicv/cumm/cumm/build/include" -I "/home/cicv/cumm/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/usr/local/lib/python3.6/dist-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -x c++-header -c /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h -o /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch 
FAILED: /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch 
g++ -MMD -MT /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch -MF /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch.d -I "/home/cicv/cumm/cumm/build/include" -I "/home/cicv/cumm/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/usr/local/lib/python3.6/dist-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -x c++-header -c /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h -o /home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h.gch 
/home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h:1:9: warning: #pragma once in main file
 #pragma once
         ^~~~
/home/cicv/cumm/cumm/build/include/tensorview_bind/TensorViewBind.h:55:1: fatal error: can’t write PCH file: No space left on device
 } // namespace tensorview_bind
 ^
compilation terminated.
[2/36] g++ -MMD -MT /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch -MF /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch.d -I "/home/cicv/cumm/cumm/build/include" -I "/home/cicv/cumm/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/usr/local/lib/python3.6/dist-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -x c++-header -c /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h -o /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch 
FAILED: /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch 
g++ -MMD -MT /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch -MF /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch.d -I "/home/cicv/cumm/cumm/build/include" -I "/home/cicv/cumm/include" -I "/usr/local/cuda-10.2/targets/aarch64-linux/include" -I "/usr/local/lib/python3.6/dist-packages/pybind11/include" -I "/usr/include/python3.6m" -I "/usr/include/python3.6m" -DTV_CUDA -std=c++14 -O3 -fPIC -x c++-header -c /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h -o /home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h.gch 
/home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h:1:9: warning: #pragma once in main file
 #pragma once
         ^~~~
/home/cicv/cumm/cumm/build/include/csrc/arrayref/ArrayPtr.h:100:1: fatal error: can’t write PCH file: No space left on device
 } // namespace csrc
 ^
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cicv/cumm/cumm/__init__.py", line 33, in <module>
    verbose=True)
  File "/home/cicv/PCCM-master/pccm/builder/pybind.py", line 141, in build_pybind
    objects_folder=objects_folder)
  File "/home/cicv/.local/lib/python3.6/site-packages/ccimport/core.py", line 182, in ccimport
    linker_to_path=linker_to_path)
  File "/home/cicv/.local/lib/python3.6/site-packages/ccimport/buildtools/writer.py", line 997, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by AI-liu** [comment]
at least   300MB  free space . problem sovled.

**Comment by Jaeger416** [comment]
How did you solve the problem?
