### ISSUE TITLE
AssertionError: assert TENSORVIEW_INCLUDE_PATH.exists()

### ISSUE THREAD

**Issue by Hetali-Vekariya** [FindDefinition/cumm#7]
I am getting this error while I run import spconv

(mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch/second/spconv$ python
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/Mon/second.pytorch/second/spconv/spconv/__init__.py", line 17, in <module>
    from .core import ConvAlgo, AlgoHint
  File "/mnt/data/Mon/second.pytorch/second/spconv/spconv/core.py", line 15, in <module>
    from cumm.gemm.main import gen_shuffle_params_v2 as gen_shuffle_params, GemmAlgoParams
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cumm/__init__.py", line 21, in <module>
    from .constants import CUMM_CPU_ONLY_BUILD, CUMM_DISABLE_JIT, PACKAGE_NAME
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cumm/constants.py", line 35, in <module>
    assert TENSORVIEW_INCLUDE_PATH.exists()
AssertionError
>>>
Can you please help me here?

If I build again using python setup.py bdist_wheel then I get the following error.

(mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch/second/spconv$ python setup.py bdist_wheel
Traceback (most recent call last):
 File "setup.py", line 153, in <module>
   from cumm.gemm.main import GemmMainUnitTest
 File "/home/ubuntu/.local/lib/python3.6/site-packages/cumm/__init__.py", line 21, in <module>
   from .constants import CUMM_CPU_ONLY_BUILD, CUMM_DISABLE_JIT, PACKAGE_NAME
 File "/home/ubuntu/.local/lib/python3.6/site-packages/cumm/constants.py", line 35, in <module>
   assert TENSORVIEW_INCLUDE_PATH.exists()
AssertionError

**Comment by Yupeng-mango** [comment]
I'm having the same problem, did you solve it?

**Comment by YuRui-Learning** [comment]
I'm having the same problem, did you solve it?

**Comment by wzy-99** [comment]
If you install from local source file, use `pip install -e .`, but not `pip install .`

**Comment by CS-Glowworm** [comment]
I'm having the same problem, did you solve it?

**Comment by Raghav-B** [comment]
> If you install from local source file, use `pip install -e .`, but not `pip install .`

For anyone encountering this in the future, this is what worked for me as well. Thanks @wzy-99
